version: '3'

tasks:
  build:
    desc: "Build the Go binary"
    cmds:
      - go build -o bin/mybinary ./cmd/...

  test:
    desc: "Run all Go tests (unit and integration)"
    cmds:
      - task: test:unit
      - task: test:integration

  test:unit:
    desc: "Run Go unit tests"
    cmds:
      - go test ./... -v

  test:integration:
    desc: "Run all Go integration tests"
    cmds:
      - go test ./... -v -tags=integration

  test:integration:anthropic:
    desc: "Run Anthropic integration tests"
    cmds:
      - go test ./llm -v -tags=integration -run TestAnthropicService

  test:integration:openai:
    desc: "Run OpenAI integration tests"
    cmds:
      - go test ./llm -v -tags=integration -run TestOpenAIService

  deps:
    desc: "Ensure gofumpt is installed"
    cmds:
      - go install mvdan.cc/gofumpt@latest
      - go get ./...

  format:
    desc: "Format Go code using gofumpt"
    cmds:
      - gofumpt -w .

  hooks:
    desc: "Run hooks defined in lefthook.yml"
    cmds:
      - lefthook run pre-commit

  lint:
    desc: "Run linters"
    cmds:
      - golangci-lint run --fast --timeout=5m ./...
    sources:
      - "**/*.go"

  install:
    desc: "install locally"
    cmds:
      - go install ./cmd/muse
