version: '3'

tasks:
  build:
    desc: "Build the Go binary"
    cmds:
      - go build -o bin/mybinary ./cmd/...

  test:
    desc: "Run all Go tests (unit and integration)"
    cmds:
      - task: test:unit
      - task: test:integration

  test:unit:
    desc: "Run Go unit tests"
    cmds:
      - go test ./... -v

  test:integration:
    desc: "Run Go integration tests"
    cmds:
      - go test ./... -v -tags=integration

  format:
    desc: "Format Go code"
    cmds:
      - go fmt ./...

  hooks:
    desc: "Run hooks defined in lefthook.yml"
    cmds:
      - lefthook run pre-commit

  lint:
    desc: "Run linters"
    cmds:
      - golangci-lint run --fast --timeout=5m ./...
    sources:
      - "**/*.go"

  install:
    desc: "install locally"
    cmds:
      - go install ./cmd/muse
