# Muse Configuration File

# Hook Configuration
hook:
  # Type of hook (currently only 'prepare-commit-msg' is supported)
  type: "prepare-commit-msg"

  # Style of commit messages to generate
  # Options: "default", "conventional", "gitmoji"
  commit_style: "conventional"

  # If true, the hook will only show the generated message without applying it
  dry_run: false

  # If true, the hook will show the generated message and ask for confirmation before applying
  preview: true

# LLM (Language Model) Configuration
llm:
  # Provider of the language model
  # Options: "openai", "anthropic", etc.
  provider: "openai"

  # OpenAI specific configuration
  model: "gpt-3.5-turbo"

  # API key for the LLM provider
  api_key: "sk-proj-xxxx"

  # Anthropic specific configuration (uncomment and modify as needed)
  # model: "claude-v1"
  # max_tokens_to_sample: 300

  # Add other provider-specific configurations as needed
# Add any other global configurations here
